import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from 'next/font/google';
import "./globals.css";
import Header from "@/components/common/Header";
import Providers from "./providers";

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'], // Latin ve Latin extended karakterler
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins', // CSS variable olarak kullanmak için
  display: 'swap', // Font yüklenene kadar sistem fontu göster
});

// Logo için Roboto Mono 300 (Light) ayarı
const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['300'], // Sadece 300 (Light) ağırlığını alıyoruz
  variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${robotoMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
